### ISSUE TITLE
What if the extraction does not have confidence value?

### ISSUE THREAD

**Issue by therealhieu** [dair-iitd/CaRB#2]
Hi,
What should I do when my extraction technique does not produce the confidence value?
Should I keep every confidence value is 1?

Hope you see and reply soon !!!

Hieu

**Comment by Aatlantise** [comment]
Your AUC values will be meaningless, but to run the code you can set every confidence value to 1. You can also apply a heuristic that assigns confidence so that confidence and length of the input sentence negatively correlates, based on a naïve assumption that a more concise sentence is likely to produce more accurate extractions.

If that is the case, you can do something like
```
def confidence(input_text):
    return 1.0/(1+0.005*len(input_text))
```
